### ISSUE TITLE
Getting Login Error

### ISSUE THREAD

**Issue by patrick-ogrady** [dreyco676/pytrends#25]
Traceback (most recent call last):
  File "general.py", line 22, in <module>
    connector = pyGTrends(google_username, google_password)
  File "/Library/Python/2.7/site-packages/pytrends/pyGTrends.py", line 51, in __init__
    self._connect()
  File "/Library/Python/2.7/site-packages/pytrends/pyGTrends.py", line 67, in _connect
    raise Exception('Cannot parse GALX out of login page')
Exception: Cannot parse GALX out of login page

Any thoughts?

**Comment by TiesdeKok** [comment]
I am having the same issue since today, I suspect that google changed the login page in some way.

**Comment by patrick-ogrady** [comment]
I am still getting the issue...did you test this?

**Comment by TiesdeKok** [comment]
You think I would suggest a fix without testing it? :stuck_out_tongue_winking_eye:
I copy pasted the code that worked for me into my comment. (Maybe something went wrong there?)

It could be that they changed something in a dynamic way, that would explain why my fix works for me but not for you. 

If you follow these steps you might be able to figure out the problem: 

1. Go to: https://accounts.google.com/ServiceLoginBoxAuth
2. View source and search for `GALX`
3. The regular expression of `line 64` should capture the GALX value after the `value` argument

In my case the problem was that the order of the arguments changed to `type` before `name`

**Comment by patrick-ogrady** [comment]
haha you can see the frustration boiling over;) Sorry about that...let me check it out. Thanks!

**Comment by patrick-ogrady** [comment]
Works perfectly!

**Comment by dreyco676** [comment]
Is there a fix that should get pull request?

**Comment by patrick-ogrady** [comment]
We both encountered an issue with login and the above fix remedied it very
nicely! I recommend following the advice above of replacing line 64 with
64-67!

**Comment by TiesdeKok** [comment]
I can send you a pull request tomorrow morning if you want.
